require('dotenv').config();
const fs = require('fs-extra');
const path = require('path');
const glob = require('glob');
const cheerio = require('cheerio');
const { minify } = require('terser');
const CleanCSS = require('clean-css');
const { minify: htmlMinify } = require('html-minifier-terser');

const isProduction = process.env.NODE_ENV === 'production';
const CHAT_PORT = process.env.CHAT_PORT || '3001';
const CHAT_PROD_URL = process.env.CHAT_PROD_URL || '';
const buildDir = path.join(__dirname, 'dist');
const componentsDir = path.join(__dirname, 'components');
const assetsToCopy = ['assets']; // CSS and JS are now processed

async function build() {
  try {
    // 1. Clean and create the build directory
    console.log(`Starting build for ${isProduction ? 'production' : 'development'}...`);
    await fs.emptyDir(buildDir);
    console.log(`Build directory '${buildDir}' is ready.`);

    // 2. Read component HTML
    const headerHtml = await fs.readFile(path.join(componentsDir, 'header.html'), 'utf-8');
    const footerHtml = await fs.readFile(path.join(componentsDir, 'footer.html'), 'utf-8');

    // 3. Process all top-level HTML files
    console.log('Processing HTML files...');
    const htmlFiles = glob.sync('*.html', { cwd: __dirname, absolute: true });

    for (const file of htmlFiles) {
      const fileName = path.basename(file);
      const fileContent = await fs.readFile(file, 'utf-8');
      const $ = cheerio.load(fileContent);

      $('#header-placeholder').replaceWith(headerHtml);
      $('#footer-placeholder').replaceWith(footerHtml);
      $('script[src="js/components.js"]').remove();

      let finalHtml = $.html();
      if (isProduction) {
        finalHtml = await htmlMinify(finalHtml, {
          collapseWhitespace: true,
          removeComments: true,
          minifyCSS: true,
          minifyJS: true,
        });
      }
      await fs.writeFile(path.join(buildDir, fileName), finalHtml);
    }
    console.log('HTML files processed.');

    // 4. Process and copy CSS files
    console.log('Processing CSS files...');
    const cssFiles = glob.sync('css/**/*.css', { cwd: __dirname, absolute: true });
    for (const file of cssFiles) {
        const content = await fs.readFile(file, 'utf-8');
        const relativePath = path.relative(__dirname, file);
        const destPath = path.join(buildDir, relativePath);
        await fs.ensureDir(path.dirname(destPath));

        if (isProduction) {
            const { styles } = new CleanCSS().minify(content);
            await fs.writeFile(destPath, styles);
        } else {
            await fs.copy(file, destPath);
        }
    }
    console.log('CSS files processed.');

    // 5. Process and copy JavaScript files
    console.log('Processing JavaScript files...');
    const jsFiles = glob.sync('js/**/*.js', { cwd: __dirname, absolute: true });
    for (const file of jsFiles) {
        const content = await fs.readFile(file, 'utf-8');
        const relativePath = path.relative(__dirname, file);
        const destPath = path.join(buildDir, relativePath);
        await fs.ensureDir(path.dirname(destPath));

        if (isProduction && !file.includes('build.js')) { // Don't minify the build script itself
            const result = await minify(content);
            await fs.writeFile(destPath, result.code);
        } else {
            await fs.copy(file, destPath);
        }
    }
    console.log('JavaScript files processed.');

    // 6. Generate chat-config.js from env variables
    console.log('Generating chat-config.js...');
    const prodUrl = CHAT_PROD_URL
        ? JSON.stringify(CHAT_PROD_URL)        // explicit override
        : `window.location.origin + '/chat'`;  // default: same protocol/host + nginx proxy path
    const chatConfigSource = [
        '// Auto-generated by build.js — do not edit directly.',
        '// To change values, edit the root .env file and rebuild.',
        `// CHAT_PORT=${CHAT_PORT}${CHAT_PROD_URL ? '  CHAT_PROD_URL=' + CHAT_PROD_URL : ''}`,
        '(function () {',
        '    var h = window.location.hostname;',
        `    window.KEYMUS_CHAT_URL = (h === 'localhost' || h === '127.0.0.1')`,
        `        ? 'http://localhost:${CHAT_PORT}'`,
        `        : ${prodUrl};`,
        '})();',
    ].join('\n');
    const chatConfigDest = path.join(buildDir, 'js', 'chat-config.js');
    await fs.ensureDir(path.dirname(chatConfigDest));
    if (isProduction) {
        const result = await minify(chatConfigSource);
        await fs.writeFile(chatConfigDest, result.code);
    } else {
        await fs.writeFile(chatConfigDest, chatConfigSource);
    }
    console.log(`chat-config.js generated (port=${CHAT_PORT}).`);

    // 7. Copy other asset directories
    console.log('Copying other assets...');
    for (const asset of assetsToCopy) {
      const sourcePath = path.join(__dirname, asset);
      const destPath = path.join(buildDir, asset);
      if (await fs.pathExists(sourcePath)) {
        await fs.copy(sourcePath, destPath);
      }
    }
    console.log('Assets copied.');

    console.log(`\nBuild for ${isProduction ? 'production' : 'development'} complete!`);
    console.log('Your static site is ready in the "dist" folder.');

  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
}

build();
